export const GET_USERS = "GET_USERS";
export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const LOADING_USERS = "LOADING_USERS";

export const GET_VIDEOS = "GET_VIDEOS";
export const ADD_VIDEO = "ADD_VIDEO";
export const ADD_VIDEO_FAIL = "ADD_VIDEO_FAIL";
export const ADD_VIDEO_SUCCESS = "ADD_VIDEO_SUCCESS";
export const DELETE_VIDEO = "DELETE_VIDEO";
export const DELETE_VIDEO_FAIL = "DELETE_VIDEO_FAIL";
// export const DELETE_USER_VIDEO = "DELETE_USER_VIDEO";
// export const DELETE_USER_VIDEO_FAIL = "DELETE_USER_VIDEO_FAIL";
export const UPDATE_VIDEO = "UPDATE_VIDEO";
export const UPDATE_VIDEO_FAIL = "UPDATE_VIDEO_FAIL";
export const UPDATE_VIDEO_SUCCESS = "UPDATE_VIDEO_SUCCESS";
export const LOADING_VIDEOS = "LOADING_VIDEOS";

export const GET_COURSES = "GET_COURSES";
export const ADD_COURSE = "ADD_COURSE";
export const ADD_COURSE_FAIL = "ADD_COURSE_FAIL";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const UPDATE_COURSE_FAIL = "UPDATE_COURSE_FAIL";
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
export const DELETE_COURSE = "DELETE_COURSE";
export const DELETE_COURSE_FAIL = "DELETE_COURSE_FAIL";
export const DELETE_COURSE_USER = "DELETE_COURSE_USER";
export const DELETE_COURSE_USER_FAIL = "DELETE_COURSE_USER_FAIL";
export const LOADING_COURSE = "LOADING_COURSE";

export const GET_COMMENTS = "GET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
export const DELETE_COMMENT_USER = "DELETE_COMMENT_USER";
export const DELETE_COMMENT_USER_FAIL = "DELETE_COMMENT_USER_FAIL";
export const LOADING_COMMENT = "LOADING_COMMENT";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
